// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJl00SVP3Oq0Fchjn7Wuh0Zn02n0EbDqs',
    appId: '1:833989760553:web:0b3e8b52b7df86567dae38',
    messagingSenderId: '833989760553',
    projectId: 'pharmaglow-a2875',
    authDomain: 'pharmaglow-a2875.firebaseapp.com',
    storageBucket: 'pharmaglow-a2875.appspot.com',
    measurementId: 'G-NZ5E2LZPGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcFeD8vVls7WDoP6t-V725f842NxngrQ',
    appId: '1:833989760553:android:0587c19db6ba4c3f7dae38',
    messagingSenderId: '833989760553',
    projectId: 'pharmaglow-a2875',
    storageBucket: 'pharmaglow-a2875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36NceFO4Ul0p2C7WAvs_3zPDXE4Jm89M',
    appId: '1:833989760553:ios:02fa4b847e2831217dae38',
    messagingSenderId: '833989760553',
    projectId: 'pharmaglow-a2875',
    storageBucket: 'pharmaglow-a2875.appspot.com',
    androidClientId: '833989760553-h3h9jn2ik7t2b8pp0dfnftsbi0nt79tf.apps.googleusercontent.com',
    iosClientId: '833989760553-cvc2l7f76076163s6g0ic18e5l0dpdls.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmaGlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36NceFO4Ul0p2C7WAvs_3zPDXE4Jm89M',
    appId: '1:833989760553:ios:02fa4b847e2831217dae38',
    messagingSenderId: '833989760553',
    projectId: 'pharmaglow-a2875',
    storageBucket: 'pharmaglow-a2875.appspot.com',
    androidClientId: '833989760553-h3h9jn2ik7t2b8pp0dfnftsbi0nt79tf.apps.googleusercontent.com',
    iosClientId: '833989760553-cvc2l7f76076163s6g0ic18e5l0dpdls.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmaGlow',
  );
}
